channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.10
  - autopep8
  - pylint
  - ipykernel
  - ipython
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - matplotlib=3.3.4
  - numpy=1.20.2
  - pandas=1.2.4
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.1
  - lightgbm=3.2.1
  - prophet=1.0.1
