channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.10
  - autopep8
  - pylint
  - ipykernel
  - ipython
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - matplotlib=3.3.4
  - numpy=1.20.2
  - pandas=1.2.4
  - fastparquet=0.5.0
  - python-snappy=0.6.0
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.1
  - nltk=3.6.2
  - xlrd=2.0.1
  - openpyxl=3.0.7
  - xlsxwriter=1.3.8
  - boto3=1.17.46
  - awscli=1.19.53
  - pip=21.1.1
  - pip:
      - sagemaker==2.45.0
